using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;

namespace XPathReader
{
    internal class XPathReaderEmitter
    {
        /// <summary>Code for a [GeneratedCode] attribute to put on the top-level generated members.</summary>
        private static readonly string _generatedCodeAttribute = $"GeneratedCodeAttribute(\"{typeof(XPathReaderGenerator).Assembly.GetName().Name}\", \"{typeof(XPathReaderGenerator).Assembly.GetName().Version}\")";
        private const string GeneratedNamespace = "XPathReader.Generated";

        private static readonly string[] _headers =
[
            "// <auto-generated/>",
            "#nullable enable",
        ];

        int _id = 0;

        private readonly HashSet<string> _names = new();

        internal void Process(SourceProductionContext context, ImmutableArray<GatheringResult> array)
        {
            foreach (GatheringResult result in array.Where(result => result.XPathToGenerate is not null))
            {
                if (_names.Contains(result.XPathToGenerate!.MethodInfo.Name))
                {
                    result.XPathToGenerate.GeneratedName = $"{result.XPathToGenerate.MethodInfo.Name}_{_id++}";
                }
                else
                {
                    _names.Add(result.XPathToGenerate.MethodInfo.Name);
                    result.XPathToGenerate.GeneratedName = result.XPathToGenerate.MethodInfo.Name;
                }


                IntendedTextWriterExtended textWriter = new IntendedTextWriterExtended(new StringWriter());
                foreach (string header in _headers)
                {
                    textWriter.WriteLine(header);
                }

                EmitRegexPartialMethod(result.XPathToGenerate, textWriter);
                EmitXPathReader(result.XPathToGenerate, textWriter);
                context.AddSource($"{result.XPathToGenerate.GeneratedName}.g.cs", textWriter.ToSourceText());
            }
        }

        private static void EmitRegexPartialMethod(XPathReaderDataToGenerate xpathToGenerate, IntendedTextWriterExtended writer)
        {
            // Emit the namespace.
            var parent = xpathToGenerate.MethodInfo;
            if (!string.IsNullOrWhiteSpace(parent.Namespace))
            {
                writer.WriteLine($"namespace {parent.Namespace}");
                writer.OpenBrace();
            }

            // Emit containing types.
            var parentClasses = new Stack<string>();
            while (parent is not null)
            {
                parentClasses.Push($"partial {parent.Keyword} {parent.Name}");
                parent = parent.Parent;
            }
            while (parentClasses.Count != 0)
            {
                writer.WriteLine($"{parentClasses.Pop()}");
                writer.OpenBrace();
            }

            // Emit the field for the generated instance.
            writer.WriteLine($"[global::System.CodeDom.Compiler.{_generatedCodeAttribute}]");
            writer.WriteLine($"private global::XPathReader.Common.XPathReader? __f{xpathToGenerate.GeneratedName} = null;");
            writer.WriteLine();

            // Emit the partial method definition.
            writer.WriteLine($"[global::System.CodeDom.Compiler.{_generatedCodeAttribute}]");
            writer.WriteLine($"{xpathToGenerate.Modifiers} global::XPathReader.Common.XPathReader{(xpathToGenerate.IsNullable ? "?" : "")} {xpathToGenerate.MemberName}()");

            writer.OpenBrace();
            writer.WriteLine($"return __f{xpathToGenerate.GeneratedName} ??= new global::{GeneratedNamespace}.{xpathToGenerate.GeneratedName}();");
            writer.CloseBrace();

            // Unwind all scopes
            while (writer.Indent != 0)
            {
                writer.CloseBrace();
            }
        }


        private void EmitXPathReader(XPathReaderDataToGenerate xPathToGenerate, IntendedTextWriterExtended writer)
        {
            writer.WriteLine($"namespace {GeneratedNamespace}");
            writer.OpenBrace();

            // We emit usings here now that we're inside of a namespace block and are no longer emitting code into
            // a user's partial type.  We can now rely on binding rules mapping to these usings and don't need to
            // use global-qualified names for the rest of the implementation.
            writer.WriteLine("using System;");
            writer.WriteLine("using System.Collections.Generic;");
            writer.WriteLine("using System.IO;");
            writer.WriteLine("using System.Threading;");
            writer.WriteLine("using System.Xml;");
            writer.WriteLine("using System.Threading.Tasks;");
            writer.WriteLine("using System.CodeDom.Compiler;");
            writer.WriteLine("using XPathReader.Common;");
            writer.WriteLine();

            writer.WriteLine($"[{_generatedCodeAttribute}]");

            writer.WriteLine($"{(xPathToGenerate.CompilationData.LanguageVersion >= 1100 ? "file" : "internal")} sealed class {xPathToGenerate.GeneratedName} : XPathReader");
            writer.OpenBrace();

            writer.WriteLine("protected override IEnumerable<ReadResult> ReadInternal(XmlReader reader)");
            writer.OpenBrace();
            writer.WriteLine("throw new NotImplementedException();");
            writer.CloseBrace();

            writer.WriteLine("protected override IAsyncEnumerable<ReadResult> ReadInternalAsync(XmlReader reader, CancellationToken cancellationToken = default)");
            writer.OpenBrace();
            writer.WriteLine("throw new NotImplementedException();");
            writer.CloseBrace();

            writer.CloseBrace();// class
            writer.CloseBrace();// namespace
        }
    }
}
