//HintName: TestClass_0.g.cs
// <auto-generated/>
#nullable enable
namespace XPathReader.TestInterface
{
    partial interface TestClass
    {
        /// <summary>Cached instance for <see cref="CreateReader"/>.</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("XPathReader.SourceGenerator", "1.0.0.0")]
        private static global::ARTX.XPath.XPathReader? __fTestClass_0;
        
        /// <remarks>
        /// Looks for the following XPath(s):<br/>
        /// <code>
        /// ○ /root/child1[1]
        /// ○ /root/child[ready()]
        /// ○ /root/child.important[1]
        /// ○ /root/child-3[@attribute]/grandchild1[name]
        /// </code>
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("XPathReader.SourceGenerator", "1.0.0.0")]
        internal static partial global::ARTX.XPath.XPathReader CreateReader
        {
            get
            {
                return __fTestClass_0 ??= new global::ARTX.XPath.Generated.TestClass_0();
            }
        }
    }
}
namespace ARTX.XPath.Generated
{
    using System.Collections.Generic;
    using System.Threading;
    using System.Xml;
    using System.CodeDom.Compiler;
    using System.Runtime.CompilerServices;
    using ARTX.XPath;
    using ARTX.XPath.Internal;
    
    [GeneratedCodeAttribute("XPathReader.SourceGenerator", "1.0.0.0")]
    file sealed class TestClass_0 : XPathReader
    {
        /// <inheritdoc/>
        protected override IEnumerable<ReadResult> ReadInternal(XmlReader reader)
        {
            using (reader)
            {
                string e_root = reader.NameTable.Add("root");
                string e_child1 = reader.NameTable.Add("child1");
                string e_child = reader.NameTable.Add("child");
                string e_child_important = reader.NameTable.Add("child.important");
                string e_child_3 = reader.NameTable.Add("child-3");
                string e_grandchild1 = reader.NameTable.Add("grandchild1");
                reader.MoveToContent();
                XPathBuilder currentXPathBuilder = new XPathBuilder();
                while (!reader.EOF)
                {
                    int counter00000001 = 0;
                    
                    if (reader.NodeType == XmlNodeType.Element)
                    {
                        if (ReferenceEquals(reader.LocalName, e_root))
                        {
                            ++counter00000001;
                            int originalLength00000002 = currentXPathBuilder.Length;
                            currentXPathBuilder.AddLevel("root");
                            if (counter00000001 != 1)
                            {
                                throw new XmlException("More than one root found in the document.");
                            }
                            int counter00000003 = 0;
                            int counter00000004 = 0;
                            int counter00000005 = 0;
                            int counter00000006 = 0;
                            
                            while (reader.NodeType != XmlNodeType.EndElement || !ReferenceEquals(reader.LocalName, e_root))
                            {
                                if (reader.NodeType == XmlNodeType.Element)
                                {
                                    if (ReferenceEquals(reader.LocalName, e_child1))
                                    {
                                        ++counter00000003;
                                        int originalLength00000007 = currentXPathBuilder.Length;
                                        currentXPathBuilder.AddLevel("child1", counter00000003);
                                        
                                        XmlReader localReader = reader.ReadSubtree();
                                        localReader.MoveToContent();
                                        yield return new ReadResult(currentXPathBuilder, localReader, "/root/child1[1]", "child1");
                                        localReader.Dispose();
                                        reader.Read();
                                        
                                        currentXPathBuilder.Length = originalLength00000007;
                                    }
                                    else if (ReferenceEquals(reader.LocalName, e_child))
                                    {
                                        ++counter00000004;
                                        int originalLength00000008 = currentXPathBuilder.Length;
                                        currentXPathBuilder.AddLevel("child", counter00000004);
                                        
                                        XmlReader localReader = reader.ReadSubtree();
                                        localReader.MoveToContent();
                                        yield return new ReadResult(currentXPathBuilder, localReader, "/root/child[ready()]", "child");
                                        localReader.Dispose();
                                        reader.Read();
                                        
                                        currentXPathBuilder.Length = originalLength00000008;
                                    }
                                    else if (ReferenceEquals(reader.LocalName, e_child_important))
                                    {
                                        ++counter00000005;
                                        int originalLength00000009 = currentXPathBuilder.Length;
                                        currentXPathBuilder.AddLevel("child.important", counter00000005);
                                        
                                        XmlReader localReader = reader.ReadSubtree();
                                        localReader.MoveToContent();
                                        yield return new ReadResult(currentXPathBuilder, localReader, "/root/child.important[1]", "child.important");
                                        localReader.Dispose();
                                        reader.Read();
                                        
                                        currentXPathBuilder.Length = originalLength00000009;
                                    }
                                    else if (ReferenceEquals(reader.LocalName, e_child_3))
                                    {
                                        ++counter00000006;
                                        int originalLength0000000a = currentXPathBuilder.Length;
                                        currentXPathBuilder.AddLevel("child-3", counter00000006);
                                        int counter0000000b = 0;
                                        
                                        while (reader.NodeType != XmlNodeType.EndElement || !ReferenceEquals(reader.LocalName, e_child_3))
                                        {
                                            if (reader.NodeType == XmlNodeType.Element)
                                            {
                                                if (ReferenceEquals(reader.LocalName, e_grandchild1))
                                                {
                                                    ++counter0000000b;
                                                    int originalLength0000000c = currentXPathBuilder.Length;
                                                    currentXPathBuilder.AddLevel("grandchild1", counter0000000b);
                                                    
                                                    XmlReader localReader = reader.ReadSubtree();
                                                    localReader.MoveToContent();
                                                    yield return new ReadResult(currentXPathBuilder, localReader, "/root/child-3[@attribute]/grandchild1[name]", "grandchild1");
                                                    localReader.Dispose();
                                                    reader.Read();
                                                    
                                                    currentXPathBuilder.Length = originalLength0000000c;
                                                }
                                                else if (!ReferenceEquals(reader.LocalName, e_child_3))
                                                {
                                                    reader.Skip();
                                                }
                                                else
                                                {
                                                    reader.Read();
                                                }
                                            }
                                            else
                                            {
                                                reader.Read();
                                            }
                                        }
                                        currentXPathBuilder.Length = originalLength0000000a;
                                    }
                                    else if (!ReferenceEquals(reader.LocalName, e_root))
                                    {
                                        reader.Skip();
                                    }
                                    else
                                    {
                                        reader.Read();
                                    }
                                }
                                else
                                {
                                    reader.Read();
                                }
                            }
                            currentXPathBuilder.Length = originalLength00000002;
                        }
                        else
                        {
                            reader.Read();
                        }
                    }
                    else
                    {
                        reader.Read();
                    }
                }
            }
        }

        /// <inheritdoc/>
        protected override async IAsyncEnumerable<ReadResult> ReadInternalAsync(XmlReader reader, [EnumeratorCancellation]CancellationToken cancellationToken)
        {
            using (reader)
            {
                string e_root = reader.NameTable.Add("root");
                string e_child1 = reader.NameTable.Add("child1");
                string e_child = reader.NameTable.Add("child");
                string e_child_important = reader.NameTable.Add("child.important");
                string e_child_3 = reader.NameTable.Add("child-3");
                string e_grandchild1 = reader.NameTable.Add("grandchild1");
                cancellationToken.ThrowIfCancellationRequested();
                await reader.MoveToContentAsync().ConfigureAwait(false);
                XPathBuilder currentXPathBuilder = new XPathBuilder();
                while (!reader.EOF)
                {
                    int counter00000001 = 0;
                    
                    if (reader.NodeType == XmlNodeType.Element)
                    {
                        if (ReferenceEquals(reader.LocalName, e_root))
                        {
                            ++counter00000001;
                            int originalLength00000002 = currentXPathBuilder.Length;
                            currentXPathBuilder.AddLevel("root");
                            if (counter00000001 != 1)
                            {
                                throw new XmlException("More than one root found in the document.");
                            }
                            int counter00000003 = 0;
                            int counter00000004 = 0;
                            int counter00000005 = 0;
                            int counter00000006 = 0;
                            
                            while (reader.NodeType != XmlNodeType.EndElement || !ReferenceEquals(reader.LocalName, e_root))
                            {
                                if (reader.NodeType == XmlNodeType.Element)
                                {
                                    if (ReferenceEquals(reader.LocalName, e_child1))
                                    {
                                        ++counter00000003;
                                        int originalLength00000007 = currentXPathBuilder.Length;
                                        currentXPathBuilder.AddLevel("child1", counter00000003);
                                        
                                        XmlReader localReader = reader.ReadSubtree();
                                        cancellationToken.ThrowIfCancellationRequested();
                                        await localReader.MoveToContentAsync().ConfigureAwait(false);
                                        yield return new ReadResult(currentXPathBuilder, localReader, "/root/child1[1]", "child1");
                                        localReader.Dispose();
                                        cancellationToken.ThrowIfCancellationRequested();
                                        await reader.ReadAsync().ConfigureAwait(false);
                                        
                                        currentXPathBuilder.Length = originalLength00000007;
                                    }
                                    else if (ReferenceEquals(reader.LocalName, e_child))
                                    {
                                        ++counter00000004;
                                        int originalLength00000008 = currentXPathBuilder.Length;
                                        currentXPathBuilder.AddLevel("child", counter00000004);
                                        
                                        XmlReader localReader = reader.ReadSubtree();
                                        cancellationToken.ThrowIfCancellationRequested();
                                        await localReader.MoveToContentAsync().ConfigureAwait(false);
                                        yield return new ReadResult(currentXPathBuilder, localReader, "/root/child[ready()]", "child");
                                        localReader.Dispose();
                                        cancellationToken.ThrowIfCancellationRequested();
                                        await reader.ReadAsync().ConfigureAwait(false);
                                        
                                        currentXPathBuilder.Length = originalLength00000008;
                                    }
                                    else if (ReferenceEquals(reader.LocalName, e_child_important))
                                    {
                                        ++counter00000005;
                                        int originalLength00000009 = currentXPathBuilder.Length;
                                        currentXPathBuilder.AddLevel("child.important", counter00000005);
                                        
                                        XmlReader localReader = reader.ReadSubtree();
                                        cancellationToken.ThrowIfCancellationRequested();
                                        await localReader.MoveToContentAsync().ConfigureAwait(false);
                                        yield return new ReadResult(currentXPathBuilder, localReader, "/root/child.important[1]", "child.important");
                                        localReader.Dispose();
                                        cancellationToken.ThrowIfCancellationRequested();
                                        await reader.ReadAsync().ConfigureAwait(false);
                                        
                                        currentXPathBuilder.Length = originalLength00000009;
                                    }
                                    else if (ReferenceEquals(reader.LocalName, e_child_3))
                                    {
                                        ++counter00000006;
                                        int originalLength0000000a = currentXPathBuilder.Length;
                                        currentXPathBuilder.AddLevel("child-3", counter00000006);
                                        int counter0000000b = 0;
                                        
                                        while (reader.NodeType != XmlNodeType.EndElement || !ReferenceEquals(reader.LocalName, e_child_3))
                                        {
                                            if (reader.NodeType == XmlNodeType.Element)
                                            {
                                                if (ReferenceEquals(reader.LocalName, e_grandchild1))
                                                {
                                                    ++counter0000000b;
                                                    int originalLength0000000c = currentXPathBuilder.Length;
                                                    currentXPathBuilder.AddLevel("grandchild1", counter0000000b);
                                                    
                                                    XmlReader localReader = reader.ReadSubtree();
                                                    cancellationToken.ThrowIfCancellationRequested();
                                                    await localReader.MoveToContentAsync().ConfigureAwait(false);
                                                    yield return new ReadResult(currentXPathBuilder, localReader, "/root/child-3[@attribute]/grandchild1[name]", "grandchild1");
                                                    localReader.Dispose();
                                                    cancellationToken.ThrowIfCancellationRequested();
                                                    await reader.ReadAsync().ConfigureAwait(false);
                                                    
                                                    currentXPathBuilder.Length = originalLength0000000c;
                                                }
                                                else if (!ReferenceEquals(reader.LocalName, e_child_3))
                                                {
                                                    cancellationToken.ThrowIfCancellationRequested();
                                                    await reader.SkipAsync().ConfigureAwait(false);
                                                }
                                                else
                                                {
                                                    cancellationToken.ThrowIfCancellationRequested();
                                                    await reader.ReadAsync().ConfigureAwait(false);
                                                }
                                            }
                                            else
                                            {
                                                cancellationToken.ThrowIfCancellationRequested();
                                                await reader.ReadAsync().ConfigureAwait(false);
                                            }
                                        }
                                        currentXPathBuilder.Length = originalLength0000000a;
                                    }
                                    else if (!ReferenceEquals(reader.LocalName, e_root))
                                    {
                                        cancellationToken.ThrowIfCancellationRequested();
                                        await reader.SkipAsync().ConfigureAwait(false);
                                    }
                                    else
                                    {
                                        cancellationToken.ThrowIfCancellationRequested();
                                        await reader.ReadAsync().ConfigureAwait(false);
                                    }
                                }
                                else
                                {
                                    cancellationToken.ThrowIfCancellationRequested();
                                    await reader.ReadAsync().ConfigureAwait(false);
                                }
                            }
                            currentXPathBuilder.Length = originalLength00000002;
                        }
                        else
                        {
                            cancellationToken.ThrowIfCancellationRequested();
                            await reader.ReadAsync().ConfigureAwait(false);
                        }
                    }
                    else
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        await reader.ReadAsync().ConfigureAwait(false);
                    }
                }
            }
        }
}
}
