//HintName: TestClass.g.cs
// <auto-generated/>
#nullable enable
namespace XPathReader.TestInterface
{
    partial struct TestClass
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("XPathReader", "1.0.0.0")]
        private global::XPathReader.Common.XPathReader? __fTestClass;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("XPathReader", "1.0.0.0")]
        public partial global::XPathReader.Common.XPathReader CreateReader()
        {
            return __fTestClass ??= new global::XPathReader.Generated.TestClass();
        }
    }
}
namespace XPathReader.Generated
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Threading;
    using System.Xml;
    using System.Threading.Tasks;
    using System.CodeDom.Compiler;
    using System.Runtime.CompilerServices;
    using XPathReader.Common;
    
    [GeneratedCodeAttribute("XPathReader", "1.0.0.0")]
    file sealed class TestClass : XPathReader
    {
        protected override IEnumerable<ReadResult> ReadInternal(XmlReader reader)
        {
            using (reader)
            {
                string e_root = reader.NameTable.Add("root");
                string e_child = reader.NameTable.Add("child");
                reader.MoveToContent();
                XPathBuilder currentXPathBuilder = new XPathBuilder();
                while (!reader.EOF)
                {
                    int counter00000001 = 0;
                    
                    if (reader.NodeType == XmlNodeType.Element)
                    {
                        if (ReferenceEquals(reader.LocalName, e_root))
                        {
                            ++counter00000001;
                            int originalLength00000002 = currentXPathBuilder.Length;
                            currentXPathBuilder.AddLevel("root");
                            if (counter00000001 != 1)
                            {
                                throw new XmlException("More than one root found in the document.");
                            }
                            int counter00000003 = 0;
                            
                            while (reader.NodeType != XmlNodeType.EndElement || !ReferenceEquals(reader.LocalName, e_root))
                            {
                                if (reader.NodeType == XmlNodeType.Element)
                                {
                                    if (ReferenceEquals(reader.LocalName, e_child))
                                    {
                                        ++counter00000003;
                                        int originalLength00000004 = currentXPathBuilder.Length;
                                        currentXPathBuilder.AddLevel("child", counter00000003);
                                        
                                        XmlReader localReader = reader.ReadSubtree();
                                        localReader.MoveToContent();
                                        yield return new ReadResult(currentXPathBuilder, localReader, new string[] { "/root/child[1]", "/root/child[1]" });
                                        localReader.Dispose();
                                        
                                        currentXPathBuilder.Length = originalLength00000004;
                                    }
                                    else if (!ReferenceEquals(reader.LocalName, e_root))
                                    {
                                        reader.Skip();
                                    }
                                    else
                                    {
                                        reader.Read();
                                    }
                                }
                                else
                                {
                                    reader.Read();
                                }
                            }
                            currentXPathBuilder.Length = originalLength00000002;
                        }
                        else
                        {
                            reader.Read();
                        }
                    }
                    else
                    {
                        reader.Read();
                    }
                }
            }
        }

        protected override async IAsyncEnumerable<ReadResult> ReadInternalAsync(XmlReader reader, [EnumeratorCancellation]CancellationToken cancellationToken)
        {
            using (reader)
            {
                string e_root = reader.NameTable.Add("root");
                string e_child = reader.NameTable.Add("child");
                cancellationToken.ThrowIfCancellationRequested();
                await reader.MoveToContentAsync().ConfigureAwait(false);
                XPathBuilder currentXPathBuilder = new XPathBuilder();
                while (!reader.EOF)
                {
                    int counter00000001 = 0;
                    
                    if (reader.NodeType == XmlNodeType.Element)
                    {
                        if (ReferenceEquals(reader.LocalName, e_root))
                        {
                            ++counter00000001;
                            int originalLength00000002 = currentXPathBuilder.Length;
                            currentXPathBuilder.AddLevel("root");
                            if (counter00000001 != 1)
                            {
                                throw new XmlException("More than one root found in the document.");
                            }
                            int counter00000003 = 0;
                            
                            while (reader.NodeType != XmlNodeType.EndElement || !ReferenceEquals(reader.LocalName, e_root))
                            {
                                if (reader.NodeType == XmlNodeType.Element)
                                {
                                    if (ReferenceEquals(reader.LocalName, e_child))
                                    {
                                        ++counter00000003;
                                        int originalLength00000004 = currentXPathBuilder.Length;
                                        currentXPathBuilder.AddLevel("child", counter00000003);
                                        
                                        XmlReader localReader = reader.ReadSubtree();
                                        cancellationToken.ThrowIfCancellationRequested();
                                        await localReader.MoveToContentAsync().ConfigureAwait(false);
                                        yield return new ReadResult(currentXPathBuilder, localReader, new string[] { "/root/child[1]", "/root/child[1]" });
                                        localReader.Dispose();
                                        
                                        currentXPathBuilder.Length = originalLength00000004;
                                    }
                                    else if (!ReferenceEquals(reader.LocalName, e_root))
                                    {
                                        cancellationToken.ThrowIfCancellationRequested();
                                        await reader.SkipAsync().ConfigureAwait(false);
                                    }
                                    else
                                    {
                                        cancellationToken.ThrowIfCancellationRequested();
                                        await reader.ReadAsync().ConfigureAwait(false);
                                    }
                                }
                                else
                                {
                                    cancellationToken.ThrowIfCancellationRequested();
                                    await reader.ReadAsync().ConfigureAwait(false);
                                }
                            }
                            currentXPathBuilder.Length = originalLength00000002;
                        }
                        else
                        {
                            cancellationToken.ThrowIfCancellationRequested();
                            await reader.ReadAsync().ConfigureAwait(false);
                        }
                    }
                    else
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        await reader.ReadAsync().ConfigureAwait(false);
                    }
                }
            }
        }
}
}
