//HintName: TestClass.g.cs
// <auto-generated/>
#nullable enable
namespace XPathReader.TestInterface
{
    partial class TestClass
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("XPathReader", "1.0.0.0")]
        private global::XPathReader.Common.XPathReader? __fTestClass = null;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("XPathReader", "1.0.0.0")]
        public partial global::XPathReader.Common.XPathReader CreateReader()
        {
            return __fTestClass ??= new global::XPathReader.Generated.TestClass();
        }
    }
}
namespace XPathReader.Generated
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Threading;
    using System.Xml;
    using System.Threading.Tasks;
    using System.CodeDom.Compiler;
    using System.Runtime.CompilerServices;
    using XPathReader.Common;
    
    [GeneratedCodeAttribute("XPathReader", "1.0.0.0")]
    file sealed class TestClass : XPathReader
    {
        protected override IEnumerable<ReadResult> ReadInternal(XmlReader reader)
        {
            using (reader)
            {
                reader.MoveToContent();
                XPathBuilder currentXPathBuilder = new XPathBuilder();
                while (!reader.EOF)
                {
                    int counter00000001 = 0;
                    object aroot00000002 = reader.NameTable.Add("root");
                    if (reader.NodeType == XmlNodeType.Element)
                    {
                        if (object.ReferenceEquals(reader.LocalName, aroot00000002))
                        {
                            ++counter00000001;
                            int originalLength00000003 = currentXPathBuilder.Length;
                            currentXPathBuilder.AddLevel("root");
                            if (counter00000001 != 1)
                            {
                                throw new XmlException("More than one root found in the document.");
                            }
                            int counter00000004 = 0;
                            int counter00000005 = 0;
                            int counter00000006 = 0;
                            object achild100000007 = reader.NameTable.Add("child1");
                            object achild00000008 = reader.NameTable.Add("child");
                            object achild300000009 = reader.NameTable.Add("child3");
                            while (reader.NodeType != XmlNodeType.EndElement || !object.ReferenceEquals(reader.LocalName, aroot00000002))
                            {
                                if (reader.NodeType == XmlNodeType.Element)
                                {
                                    if (object.ReferenceEquals(reader.LocalName, achild100000007))
                                    {
                                        ++counter00000004;
                                        int originalLength0000000a = currentXPathBuilder.Length;
                                        currentXPathBuilder.AddLevel("child1", counter00000004);
                                        XmlReader localReader = reader.ReadSubtree();
                                        localReader.MoveToContent();
                                        yield return new ReadResult(currentXPathBuilder, localReader, "/root/child1");
                                        localReader.Dispose();
                                        currentXPathBuilder.Length = originalLength0000000a;
                                    }
                                    else if (object.ReferenceEquals(reader.LocalName, achild00000008))
                                    {
                                        ++counter00000005;
                                        int originalLength0000000b = currentXPathBuilder.Length;
                                        currentXPathBuilder.AddLevel("child", counter00000005);
                                        XmlReader localReader = reader.ReadSubtree();
                                        localReader.MoveToContent();
                                        yield return new ReadResult(currentXPathBuilder, localReader, new string[] { "/root/child", "/root/child/" });
                                        localReader.Dispose();
                                        currentXPathBuilder.Length = originalLength0000000b;
                                    }
                                    else if (object.ReferenceEquals(reader.LocalName, achild300000009))
                                    {
                                        ++counter00000006;
                                        int originalLength0000000c = currentXPathBuilder.Length;
                                        currentXPathBuilder.AddLevel("child3", counter00000006);
                                        int counter0000000d = 0;
                                        object agrandchild10000000e = reader.NameTable.Add("grandchild1");
                                        while (reader.NodeType != XmlNodeType.EndElement || !object.ReferenceEquals(reader.LocalName, achild300000009))
                                        {
                                            if (reader.NodeType == XmlNodeType.Element)
                                            {
                                                if (object.ReferenceEquals(reader.LocalName, agrandchild10000000e))
                                                {
                                                    ++counter0000000d;
                                                    int originalLength0000000f = currentXPathBuilder.Length;
                                                    currentXPathBuilder.AddLevel("grandchild1", counter0000000d);
                                                    XmlReader localReader = reader.ReadSubtree();
                                                    localReader.MoveToContent();
                                                    yield return new ReadResult(currentXPathBuilder, localReader, "root/child3/grandchild1");
                                                    localReader.Dispose();
                                                    currentXPathBuilder.Length = originalLength0000000f;
                                                }
                                                else if (!object.ReferenceEquals(reader.LocalName, achild300000009))
                                                {
                                                    reader.Skip();
                                                }
                                                else
                                                {
                                                    reader.Read();
                                                }
                                            }
                                            else
                                            {
                                                reader.Read();
                                            }
                                        }
                                        currentXPathBuilder.Length = originalLength0000000c;
                                    }
                                    else if (!object.ReferenceEquals(reader.LocalName, aroot00000002))
                                    {
                                        reader.Skip();
                                    }
                                    else
                                    {
                                        reader.Read();
                                    }
                                }
                                else
                                {
                                    reader.Read();
                                }
                            }
                            currentXPathBuilder.Length = originalLength00000003;
                        }
                        else
                        {
                            reader.Read();
                        }
                    }
                    else
                    {
                        reader.Read();
                    }
                }
            }
        }

        protected override async IAsyncEnumerable<ReadResult> ReadInternalAsync(XmlReader reader, [EnumeratorCancellation]CancellationToken cancellationToken)
        {
            using (reader)
            {
                cancellationToken.ThrowIfCancellationRequested();
                await reader.MoveToContentAsync().ConfigureAwait(false);
                XPathBuilder currentXPathBuilder = new XPathBuilder();
                while (!reader.EOF)
                {
                    int counter00000001 = 0;
                    object aroot00000002 = reader.NameTable.Add("root");
                    if (reader.NodeType == XmlNodeType.Element)
                    {
                        if (object.ReferenceEquals(reader.LocalName, aroot00000002))
                        {
                            ++counter00000001;
                            int originalLength00000003 = currentXPathBuilder.Length;
                            currentXPathBuilder.AddLevel("root");
                            if (counter00000001 != 1)
                            {
                                throw new XmlException("More than one root found in the document.");
                            }
                            int counter00000004 = 0;
                            int counter00000005 = 0;
                            int counter00000006 = 0;
                            object achild100000007 = reader.NameTable.Add("child1");
                            object achild00000008 = reader.NameTable.Add("child");
                            object achild300000009 = reader.NameTable.Add("child3");
                            while (reader.NodeType != XmlNodeType.EndElement || !object.ReferenceEquals(reader.LocalName, aroot00000002))
                            {
                                if (reader.NodeType == XmlNodeType.Element)
                                {
                                    if (object.ReferenceEquals(reader.LocalName, achild100000007))
                                    {
                                        ++counter00000004;
                                        int originalLength0000000a = currentXPathBuilder.Length;
                                        currentXPathBuilder.AddLevel("child1", counter00000004);
                                        XmlReader localReader = reader.ReadSubtree();
                                        cancellationToken.ThrowIfCancellationRequested();
                                        await localReader.MoveToContentAsync().ConfigureAwait(false);
                                        yield return new ReadResult(currentXPathBuilder, localReader, "/root/child1");
                                        localReader.Dispose();
                                        currentXPathBuilder.Length = originalLength0000000a;
                                    }
                                    else if (object.ReferenceEquals(reader.LocalName, achild00000008))
                                    {
                                        ++counter00000005;
                                        int originalLength0000000b = currentXPathBuilder.Length;
                                        currentXPathBuilder.AddLevel("child", counter00000005);
                                        XmlReader localReader = reader.ReadSubtree();
                                        cancellationToken.ThrowIfCancellationRequested();
                                        await localReader.MoveToContentAsync().ConfigureAwait(false);
                                        yield return new ReadResult(currentXPathBuilder, localReader, new string[] { "/root/child", "/root/child/" });
                                        localReader.Dispose();
                                        currentXPathBuilder.Length = originalLength0000000b;
                                    }
                                    else if (object.ReferenceEquals(reader.LocalName, achild300000009))
                                    {
                                        ++counter00000006;
                                        int originalLength0000000c = currentXPathBuilder.Length;
                                        currentXPathBuilder.AddLevel("child3", counter00000006);
                                        int counter0000000d = 0;
                                        object agrandchild10000000e = reader.NameTable.Add("grandchild1");
                                        while (reader.NodeType != XmlNodeType.EndElement || !object.ReferenceEquals(reader.LocalName, achild300000009))
                                        {
                                            if (reader.NodeType == XmlNodeType.Element)
                                            {
                                                if (object.ReferenceEquals(reader.LocalName, agrandchild10000000e))
                                                {
                                                    ++counter0000000d;
                                                    int originalLength0000000f = currentXPathBuilder.Length;
                                                    currentXPathBuilder.AddLevel("grandchild1", counter0000000d);
                                                    XmlReader localReader = reader.ReadSubtree();
                                                    cancellationToken.ThrowIfCancellationRequested();
                                                    await localReader.MoveToContentAsync().ConfigureAwait(false);
                                                    yield return new ReadResult(currentXPathBuilder, localReader, "root/child3/grandchild1");
                                                    localReader.Dispose();
                                                    currentXPathBuilder.Length = originalLength0000000f;
                                                }
                                                else if (!object.ReferenceEquals(reader.LocalName, achild300000009))
                                                {
                                                    cancellationToken.ThrowIfCancellationRequested();
                                                    await reader.SkipAsync().ConfigureAwait(false);
                                                }
                                                else
                                                {
                                                    cancellationToken.ThrowIfCancellationRequested();
                                                    await reader.ReadAsync().ConfigureAwait(false);
                                                }
                                            }
                                            else
                                            {
                                                cancellationToken.ThrowIfCancellationRequested();
                                                await reader.ReadAsync().ConfigureAwait(false);
                                            }
                                        }
                                        currentXPathBuilder.Length = originalLength0000000c;
                                    }
                                    else if (!object.ReferenceEquals(reader.LocalName, aroot00000002))
                                    {
                                        cancellationToken.ThrowIfCancellationRequested();
                                        await reader.SkipAsync().ConfigureAwait(false);
                                    }
                                    else
                                    {
                                        cancellationToken.ThrowIfCancellationRequested();
                                        await reader.ReadAsync().ConfigureAwait(false);
                                    }
                                }
                                else
                                {
                                    cancellationToken.ThrowIfCancellationRequested();
                                    await reader.ReadAsync().ConfigureAwait(false);
                                }
                            }
                            currentXPathBuilder.Length = originalLength00000003;
                        }
                        else
                        {
                            cancellationToken.ThrowIfCancellationRequested();
                            await reader.ReadAsync().ConfigureAwait(false);
                        }
                    }
                    else
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        await reader.ReadAsync().ConfigureAwait(false);
                    }
                }
            }
        }
}
}
